/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountsResponseLinksInner
 */
export interface AccountsResponseLinksInner {
    /**
     * 
     * @type {string}
     * @memberof AccountsResponseLinksInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsResponseLinksInner
     */
    'label'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountsResponseLinksInner
     */
    'active'?: boolean;
}

