/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountResponse
 */
export interface AccountResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'surname'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountResponse
     */
    'email'?: string;
}

