/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthAuthorization } from './auth-authorization';

/**
 * 
 * @export
 * @interface Auth
 */
export interface Auth {
    /**
     * 
     * @type {string}
     * @memberof Auth
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Auth
     */
    'accountId'?: string;
    /**
     * 
     * @type {AuthAuthorization}
     * @memberof Auth
     */
    'authorization'?: AuthAuthorization;
}

