/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentResponse
 */
export interface CommentResponse {
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'todo_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'account_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentResponse
     */
    'account_username'?: string;
}

