/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateTodo201ResponseData } from './create-todo201-response-data';

/**
 * 
 * @export
 * @interface CreateTodo201Response
 */
export interface CreateTodo201Response {
    /**
     * 
     * @type {CreateTodo201ResponseData}
     * @memberof CreateTodo201Response
     */
    'data'?: CreateTodo201ResponseData;
    /**
     * 
     * @type {string}
     * @memberof CreateTodo201Response
     */
    'message'?: string;
}

