/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountsUsernames } from './accounts-usernames';

/**
 * 
 * @export
 * @interface GetAllUsernames200Response
 */
export interface GetAllUsernames200Response {
    /**
     * 
     * @type {Array<AccountsUsernames>}
     * @memberof GetAllUsernames200Response
     */
    'data'?: Array<AccountsUsernames>;
    /**
     * 
     * @type {string}
     * @memberof GetAllUsernames200Response
     */
    'message'?: string;
}

