/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommentResponse } from './comment-response';

/**
 * 
 * @export
 * @interface GetComment200Response
 */
export interface GetComment200Response {
    /**
     * 
     * @type {CommentResponse}
     * @memberof GetComment200Response
     */
    'data'?: CommentResponse;
    /**
     * 
     * @type {string}
     * @memberof GetComment200Response
     */
    'message'?: string;
}

