/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetComment404Response
 */
export interface GetComment404Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetComment404Response
     */
    'data'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetComment404Response
     */
    'message'?: string;
}

