/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Refresh200ResponseDataAuthorization } from './refresh200-response-data-authorization';

/**
 * 
 * @export
 * @interface Refresh200ResponseData
 */
export interface Refresh200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof Refresh200ResponseData
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Refresh200ResponseData
     */
    'accountId'?: string;
    /**
     * 
     * @type {Refresh200ResponseDataAuthorization}
     * @memberof Refresh200ResponseData
     */
    'authorization'?: Refresh200ResponseDataAuthorization;
}

