/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Refresh200ResponseData } from './refresh200-response-data';

/**
 * 
 * @export
 * @interface Refresh200Response
 */
export interface Refresh200Response {
    /**
     * 
     * @type {Refresh200ResponseData}
     * @memberof Refresh200Response
     */
    'data'?: Refresh200ResponseData;
    /**
     * 
     * @type {string}
     * @memberof Refresh200Response
     */
    'message'?: string;
}

