/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SortFilterParams
 */
export interface SortFilterParams {
    /**
     * 
     * @type {number}
     * @memberof SortFilterParams
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof SortFilterParams
     */
    'page'?: number;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'sortBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'sortValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'filterBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'filterValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof SortFilterParams
     */
    'end'?: string;
}

