/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountsResponseLinksInner } from './accounts-response-links-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { TodoResponse } from './todo-response';

/**
 * 
 * @export
 * @interface TodosResponse
 */
export interface TodosResponse {
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'current_page'?: number;
    /**
     * 
     * @type {Array<TodoResponse>}
     * @memberof TodosResponse
     */
    'data'?: Array<TodoResponse>;
    /**
     * 
     * @type {string}
     * @memberof TodosResponse
     */
    'first_page_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'from'?: number;
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'last_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof TodosResponse
     */
    'last_page_url'?: string;
    /**
     * 
     * @type {Array<AccountsResponseLinksInner>}
     * @memberof TodosResponse
     */
    'links'?: Array<AccountsResponseLinksInner>;
    /**
     * 
     * @type {string}
     * @memberof TodosResponse
     */
    'next_page_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodosResponse
     */
    'path'?: string;
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'per_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof TodosResponse
     */
    'prev_page_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'to'?: number;
    /**
     * 
     * @type {number}
     * @memberof TodosResponse
     */
    'total'?: number;
}

