/* tslint:disable */
/* eslint-disable */
/**
 * S2I final
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TodoResponse
 */
export interface TodoResponse {
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'note'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'category'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoResponse
     */
    'checked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoResponse
     */
    'account_id'?: string;
}

